// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filtersrv_header.proto

package com.alibaba.rocketmq.common.protocol.protobuf;

public final class FiltersrvHeader {
  private FiltersrvHeader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RegisterFilterServerRequestHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerRequestHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string filterServerAddr = 1;</code>
     */
    boolean hasFilterServerAddr();
    /**
     * <code>required string filterServerAddr = 1;</code>
     */
    java.lang.String getFilterServerAddr();
    /**
     * <code>required string filterServerAddr = 1;</code>
     */
    com.google.protobuf.ByteString
        getFilterServerAddrBytes();
  }
  /**
   * Protobuf type {@code com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerRequestHeader}
   *
   * <pre>
   * filtersrv_header
   * </pre>
   */
  public static final class RegisterFilterServerRequestHeader extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerRequestHeader)
      RegisterFilterServerRequestHeaderOrBuilder {
    // Use RegisterFilterServerRequestHeader.newBuilder() to construct.
    private RegisterFilterServerRequestHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RegisterFilterServerRequestHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RegisterFilterServerRequestHeader defaultInstance;
    public static RegisterFilterServerRequestHeader getDefaultInstance() {
      return defaultInstance;
    }

    public RegisterFilterServerRequestHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RegisterFilterServerRequestHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              filterServerAddr_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerRequestHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerRequestHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader.class, com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<RegisterFilterServerRequestHeader> PARSER =
        new com.google.protobuf.AbstractParser<RegisterFilterServerRequestHeader>() {
      public RegisterFilterServerRequestHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegisterFilterServerRequestHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterFilterServerRequestHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FILTERSERVERADDR_FIELD_NUMBER = 1;
    private java.lang.Object filterServerAddr_;
    /**
     * <code>required string filterServerAddr = 1;</code>
     */
    public boolean hasFilterServerAddr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string filterServerAddr = 1;</code>
     */
    public java.lang.String getFilterServerAddr() {
      java.lang.Object ref = filterServerAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filterServerAddr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string filterServerAddr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFilterServerAddrBytes() {
      java.lang.Object ref = filterServerAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filterServerAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      filterServerAddr_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFilterServerAddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFilterServerAddrBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFilterServerAddrBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerRequestHeader}
     *
     * <pre>
     * filtersrv_header
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerRequestHeader)
        com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerRequestHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerRequestHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader.class, com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader.Builder.class);
      }

      // Construct using com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        filterServerAddr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerRequestHeader_descriptor;
      }

      public com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader getDefaultInstanceForType() {
        return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader.getDefaultInstance();
      }

      public com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader build() {
        com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader buildPartial() {
        com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader result = new com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filterServerAddr_ = filterServerAddr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader) {
          return mergeFrom((com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader other) {
        if (other == com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader.getDefaultInstance()) return this;
        if (other.hasFilterServerAddr()) {
          bitField0_ |= 0x00000001;
          filterServerAddr_ = other.filterServerAddr_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFilterServerAddr()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerRequestHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object filterServerAddr_ = "";
      /**
       * <code>required string filterServerAddr = 1;</code>
       */
      public boolean hasFilterServerAddr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string filterServerAddr = 1;</code>
       */
      public java.lang.String getFilterServerAddr() {
        java.lang.Object ref = filterServerAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            filterServerAddr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string filterServerAddr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFilterServerAddrBytes() {
        java.lang.Object ref = filterServerAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filterServerAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string filterServerAddr = 1;</code>
       */
      public Builder setFilterServerAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filterServerAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string filterServerAddr = 1;</code>
       */
      public Builder clearFilterServerAddr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filterServerAddr_ = getDefaultInstance().getFilterServerAddr();
        onChanged();
        return this;
      }
      /**
       * <code>required string filterServerAddr = 1;</code>
       */
      public Builder setFilterServerAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filterServerAddr_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerRequestHeader)
    }

    static {
      defaultInstance = new RegisterFilterServerRequestHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerRequestHeader)
  }

  public interface RegisterFilterServerResponseHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerResponseHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string brokerName = 1;</code>
     */
    boolean hasBrokerName();
    /**
     * <code>required string brokerName = 1;</code>
     */
    java.lang.String getBrokerName();
    /**
     * <code>required string brokerName = 1;</code>
     */
    com.google.protobuf.ByteString
        getBrokerNameBytes();

    /**
     * <code>required int64 brokerId = 2;</code>
     */
    boolean hasBrokerId();
    /**
     * <code>required int64 brokerId = 2;</code>
     */
    long getBrokerId();
  }
  /**
   * Protobuf type {@code com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerResponseHeader}
   */
  public static final class RegisterFilterServerResponseHeader extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerResponseHeader)
      RegisterFilterServerResponseHeaderOrBuilder {
    // Use RegisterFilterServerResponseHeader.newBuilder() to construct.
    private RegisterFilterServerResponseHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RegisterFilterServerResponseHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RegisterFilterServerResponseHeader defaultInstance;
    public static RegisterFilterServerResponseHeader getDefaultInstance() {
      return defaultInstance;
    }

    public RegisterFilterServerResponseHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RegisterFilterServerResponseHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              brokerName_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              brokerId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerResponseHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerResponseHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader.class, com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<RegisterFilterServerResponseHeader> PARSER =
        new com.google.protobuf.AbstractParser<RegisterFilterServerResponseHeader>() {
      public RegisterFilterServerResponseHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegisterFilterServerResponseHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterFilterServerResponseHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BROKERNAME_FIELD_NUMBER = 1;
    private java.lang.Object brokerName_;
    /**
     * <code>required string brokerName = 1;</code>
     */
    public boolean hasBrokerName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string brokerName = 1;</code>
     */
    public java.lang.String getBrokerName() {
      java.lang.Object ref = brokerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          brokerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string brokerName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBrokerNameBytes() {
      java.lang.Object ref = brokerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brokerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BROKERID_FIELD_NUMBER = 2;
    private long brokerId_;
    /**
     * <code>required int64 brokerId = 2;</code>
     */
    public boolean hasBrokerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 brokerId = 2;</code>
     */
    public long getBrokerId() {
      return brokerId_;
    }

    private void initFields() {
      brokerName_ = "";
      brokerId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBrokerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBrokerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBrokerNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, brokerId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBrokerNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, brokerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerResponseHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerResponseHeader)
        com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerResponseHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerResponseHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader.class, com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader.Builder.class);
      }

      // Construct using com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        brokerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        brokerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerResponseHeader_descriptor;
      }

      public com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader getDefaultInstanceForType() {
        return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader.getDefaultInstance();
      }

      public com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader build() {
        com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader buildPartial() {
        com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader result = new com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.brokerName_ = brokerName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.brokerId_ = brokerId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader) {
          return mergeFrom((com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader other) {
        if (other == com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader.getDefaultInstance()) return this;
        if (other.hasBrokerName()) {
          bitField0_ |= 0x00000001;
          brokerName_ = other.brokerName_;
          onChanged();
        }
        if (other.hasBrokerId()) {
          setBrokerId(other.getBrokerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBrokerName()) {
          
          return false;
        }
        if (!hasBrokerId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterFilterServerResponseHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object brokerName_ = "";
      /**
       * <code>required string brokerName = 1;</code>
       */
      public boolean hasBrokerName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string brokerName = 1;</code>
       */
      public java.lang.String getBrokerName() {
        java.lang.Object ref = brokerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            brokerName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string brokerName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBrokerNameBytes() {
        java.lang.Object ref = brokerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brokerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string brokerName = 1;</code>
       */
      public Builder setBrokerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brokerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string brokerName = 1;</code>
       */
      public Builder clearBrokerName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        brokerName_ = getDefaultInstance().getBrokerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string brokerName = 1;</code>
       */
      public Builder setBrokerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brokerName_ = value;
        onChanged();
        return this;
      }

      private long brokerId_ ;
      /**
       * <code>required int64 brokerId = 2;</code>
       */
      public boolean hasBrokerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 brokerId = 2;</code>
       */
      public long getBrokerId() {
        return brokerId_;
      }
      /**
       * <code>required int64 brokerId = 2;</code>
       */
      public Builder setBrokerId(long value) {
        bitField0_ |= 0x00000002;
        brokerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 brokerId = 2;</code>
       */
      public Builder clearBrokerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        brokerId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerResponseHeader)
    }

    static {
      defaultInstance = new RegisterFilterServerResponseHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.alibaba.rocketmq.common.protocol.protobuf.RegisterFilterServerResponseHeader)
  }

  public interface RegisterMessageFilterClassRequestHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.alibaba.rocketmq.common.protocol.protobuf.RegisterMessageFilterClassRequestHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string consumerGroup = 1;</code>
     */
    boolean hasConsumerGroup();
    /**
     * <code>required string consumerGroup = 1;</code>
     */
    java.lang.String getConsumerGroup();
    /**
     * <code>required string consumerGroup = 1;</code>
     */
    com.google.protobuf.ByteString
        getConsumerGroupBytes();

    /**
     * <code>required string topic = 2;</code>
     */
    boolean hasTopic();
    /**
     * <code>required string topic = 2;</code>
     */
    java.lang.String getTopic();
    /**
     * <code>required string topic = 2;</code>
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>required string className = 3;</code>
     */
    boolean hasClassName();
    /**
     * <code>required string className = 3;</code>
     */
    java.lang.String getClassName();
    /**
     * <code>required string className = 3;</code>
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>required int32 classCRC = 4;</code>
     */
    boolean hasClassCRC();
    /**
     * <code>required int32 classCRC = 4;</code>
     */
    int getClassCRC();
  }
  /**
   * Protobuf type {@code com.alibaba.rocketmq.common.protocol.protobuf.RegisterMessageFilterClassRequestHeader}
   */
  public static final class RegisterMessageFilterClassRequestHeader extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.alibaba.rocketmq.common.protocol.protobuf.RegisterMessageFilterClassRequestHeader)
      RegisterMessageFilterClassRequestHeaderOrBuilder {
    // Use RegisterMessageFilterClassRequestHeader.newBuilder() to construct.
    private RegisterMessageFilterClassRequestHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RegisterMessageFilterClassRequestHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RegisterMessageFilterClassRequestHeader defaultInstance;
    public static RegisterMessageFilterClassRequestHeader getDefaultInstance() {
      return defaultInstance;
    }

    public RegisterMessageFilterClassRequestHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RegisterMessageFilterClassRequestHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              consumerGroup_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              topic_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              className_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              classCRC_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterMessageFilterClassRequestHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterMessageFilterClassRequestHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader.class, com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<RegisterMessageFilterClassRequestHeader> PARSER =
        new com.google.protobuf.AbstractParser<RegisterMessageFilterClassRequestHeader>() {
      public RegisterMessageFilterClassRequestHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegisterMessageFilterClassRequestHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterMessageFilterClassRequestHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CONSUMERGROUP_FIELD_NUMBER = 1;
    private java.lang.Object consumerGroup_;
    /**
     * <code>required string consumerGroup = 1;</code>
     */
    public boolean hasConsumerGroup() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string consumerGroup = 1;</code>
     */
    public java.lang.String getConsumerGroup() {
      java.lang.Object ref = consumerGroup_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          consumerGroup_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string consumerGroup = 1;</code>
     */
    public com.google.protobuf.ByteString
        getConsumerGroupBytes() {
      java.lang.Object ref = consumerGroup_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumerGroup_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOPIC_FIELD_NUMBER = 2;
    private java.lang.Object topic_;
    /**
     * <code>required string topic = 2;</code>
     */
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string topic = 2;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          topic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string topic = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASSNAME_FIELD_NUMBER = 3;
    private java.lang.Object className_;
    /**
     * <code>required string className = 3;</code>
     */
    public boolean hasClassName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string className = 3;</code>
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          className_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string className = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASSCRC_FIELD_NUMBER = 4;
    private int classCRC_;
    /**
     * <code>required int32 classCRC = 4;</code>
     */
    public boolean hasClassCRC() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 classCRC = 4;</code>
     */
    public int getClassCRC() {
      return classCRC_;
    }

    private void initFields() {
      consumerGroup_ = "";
      topic_ = "";
      className_ = "";
      classCRC_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasConsumerGroup()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTopic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClassName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClassCRC()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getConsumerGroupBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTopicBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getClassNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, classCRC_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getConsumerGroupBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTopicBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getClassNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, classCRC_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.alibaba.rocketmq.common.protocol.protobuf.RegisterMessageFilterClassRequestHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.alibaba.rocketmq.common.protocol.protobuf.RegisterMessageFilterClassRequestHeader)
        com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterMessageFilterClassRequestHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterMessageFilterClassRequestHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader.class, com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader.Builder.class);
      }

      // Construct using com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        consumerGroup_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        topic_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        className_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        classCRC_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterMessageFilterClassRequestHeader_descriptor;
      }

      public com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader getDefaultInstanceForType() {
        return com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader.getDefaultInstance();
      }

      public com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader build() {
        com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader buildPartial() {
        com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader result = new com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.consumerGroup_ = consumerGroup_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.topic_ = topic_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.className_ = className_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.classCRC_ = classCRC_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader) {
          return mergeFrom((com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader other) {
        if (other == com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader.getDefaultInstance()) return this;
        if (other.hasConsumerGroup()) {
          bitField0_ |= 0x00000001;
          consumerGroup_ = other.consumerGroup_;
          onChanged();
        }
        if (other.hasTopic()) {
          bitField0_ |= 0x00000002;
          topic_ = other.topic_;
          onChanged();
        }
        if (other.hasClassName()) {
          bitField0_ |= 0x00000004;
          className_ = other.className_;
          onChanged();
        }
        if (other.hasClassCRC()) {
          setClassCRC(other.getClassCRC());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasConsumerGroup()) {
          
          return false;
        }
        if (!hasTopic()) {
          
          return false;
        }
        if (!hasClassName()) {
          
          return false;
        }
        if (!hasClassCRC()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.rocketmq.common.protocol.protobuf.FiltersrvHeader.RegisterMessageFilterClassRequestHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object consumerGroup_ = "";
      /**
       * <code>required string consumerGroup = 1;</code>
       */
      public boolean hasConsumerGroup() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string consumerGroup = 1;</code>
       */
      public java.lang.String getConsumerGroup() {
        java.lang.Object ref = consumerGroup_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            consumerGroup_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string consumerGroup = 1;</code>
       */
      public com.google.protobuf.ByteString
          getConsumerGroupBytes() {
        java.lang.Object ref = consumerGroup_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          consumerGroup_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string consumerGroup = 1;</code>
       */
      public Builder setConsumerGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        consumerGroup_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string consumerGroup = 1;</code>
       */
      public Builder clearConsumerGroup() {
        bitField0_ = (bitField0_ & ~0x00000001);
        consumerGroup_ = getDefaultInstance().getConsumerGroup();
        onChanged();
        return this;
      }
      /**
       * <code>required string consumerGroup = 1;</code>
       */
      public Builder setConsumerGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        consumerGroup_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object topic_ = "";
      /**
       * <code>required string topic = 2;</code>
       */
      public boolean hasTopic() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string topic = 2;</code>
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            topic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string topic = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string topic = 2;</code>
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 2;</code>
       */
      public Builder clearTopic() {
        bitField0_ = (bitField0_ & ~0x00000002);
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 2;</code>
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        topic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object className_ = "";
      /**
       * <code>required string className = 3;</code>
       */
      public boolean hasClassName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string className = 3;</code>
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            className_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string className = 3;</code>
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string className = 3;</code>
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string className = 3;</code>
       */
      public Builder clearClassName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <code>required string className = 3;</code>
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        className_ = value;
        onChanged();
        return this;
      }

      private int classCRC_ ;
      /**
       * <code>required int32 classCRC = 4;</code>
       */
      public boolean hasClassCRC() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 classCRC = 4;</code>
       */
      public int getClassCRC() {
        return classCRC_;
      }
      /**
       * <code>required int32 classCRC = 4;</code>
       */
      public Builder setClassCRC(int value) {
        bitField0_ |= 0x00000008;
        classCRC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 classCRC = 4;</code>
       */
      public Builder clearClassCRC() {
        bitField0_ = (bitField0_ & ~0x00000008);
        classCRC_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.alibaba.rocketmq.common.protocol.protobuf.RegisterMessageFilterClassRequestHeader)
    }

    static {
      defaultInstance = new RegisterMessageFilterClassRequestHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.alibaba.rocketmq.common.protocol.protobuf.RegisterMessageFilterClassRequestHeader)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerRequestHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerRequestHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerResponseHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerResponseHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterMessageFilterClassRequestHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterMessageFilterClassRequestHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026filtersrv_header.proto\022-com.alibaba.ro" +
      "cketmq.common.protocol.protobuf\"=\n!Regis" +
      "terFilterServerRequestHeader\022\030\n\020filterSe" +
      "rverAddr\030\001 \002(\t\"J\n\"RegisterFilterServerRe" +
      "sponseHeader\022\022\n\nbrokerName\030\001 \002(\t\022\020\n\010brok" +
      "erId\030\002 \002(\003\"t\n\'RegisterMessageFilterClass" +
      "RequestHeader\022\025\n\rconsumerGroup\030\001 \002(\t\022\r\n\005" +
      "topic\030\002 \002(\t\022\021\n\tclassName\030\003 \002(\t\022\020\n\010classC" +
      "RC\030\004 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerRequestHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerRequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerRequestHeader_descriptor,
        new java.lang.String[] { "FilterServerAddr", });
    internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerResponseHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerResponseHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterFilterServerResponseHeader_descriptor,
        new java.lang.String[] { "BrokerName", "BrokerId", });
    internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterMessageFilterClassRequestHeader_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterMessageFilterClassRequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_alibaba_rocketmq_common_protocol_protobuf_RegisterMessageFilterClassRequestHeader_descriptor,
        new java.lang.String[] { "ConsumerGroup", "Topic", "ClassName", "ClassCRC", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
